### PR TITLE
Jira Card: DEV-2064 Irina-Mike  make sure pdfreactor service restarts…

### PR DESCRIPTION
**Pull request by imuchnik**
… on reboot-

Modify ansible playbook to place the init.d script in the correct dir and enable it as a service

### CODE REVIEW

**Comment by vccabral** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by vccabral** [comment]
LGTM

**Comment by m3brown** [comment]
Just gave it a whirl and it's working great!  The following commands worked like a charm:

```
sudo service pdfreactorwebservice restart
chkconfig | grep pdf
```

**Comment by vccabral** [comment]
cool cool cool

**Pull request merged**
